apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-qaqsecol
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-qaqsecol:dc934881e051c930d876e52054a1a301d58545fd@sha256:e2a5d76945e7421a591f61fe229f6434ac552cb459f9760dbb226819f91f019e
          name: container-image
